Fix unexpected argument autodetection_retry
Solves the following failure on startup:
```
python.d WARNING: plugin[main] : sqlserver[job_name] : unhandled exception on check : TypeError("connect(
) got an unexpected keyword argument 'autodetection_retry'",), skipping the job
```

Since we are updating `params` with `self.configuration` before calling `pymssql.connect(**params)`, we are adding `autodetection_retry` as an extraneous keyword argument. This causes an unhandled exception, preventing startup.